#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy
# edit config file
server_config=\
"
frontend  besthor_frontend
        bind *:80
        mode http
        default_backend besthor_backend
backend besthor_backend
        balance roundrobin
        server 176572-web-01 100.26.231.82:80 check
        server 176572-web-02 100.26.171.172:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg
# Restart the Nginx service
sudo service haproxy restart
