#!/usr/bin/env bash
#Script that config an Ubunto server

cp /ect/hosts /etc/hosts.old
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts/new
cp -f ~hosts.new /etc/hosts
